import Link from 'next/link'
import { notFound } from 'next/navigation'

import { NinaJobDetail } from '@/components/nina/NinaJobDetail'
import { AppShell, ScreenHeader } from '@/components/ui/AppShell'
import { requireUserId } from '@/lib/auth/requireUserId'
import { jakartaDayOf } from '@/lib/date/ranges'
import { formatDayCompact } from '@/lib/format'
import { isValidId } from '@/lib/id'
import { SESSION_PARAM } from '@/lib/nina/active'
import { getNinaImageJobDetail } from '@/lib/nina/imagejobs'
import {
  NINA_JOBS_HREF,
  NINA_JOB_STAGE_LABEL,
  jobErrorLabel,
  jobStage,
  planJobJump,
  planJobPhoto,
} from '@/lib/nina/jobview'
import { getNinaJobPhoto, getNinaJobPhotoBubble } from '@/lib/nina/queries'

/**
 * `/nina/jobs/[id]` — R1's image-generation detail page.
 *
 * ── THE ID IN THE URL IS A CLAIM; THE `WHERE` IS THE FACT (INVARIANT 5) ───────────────────────
 * `isValidId` first, on `/r/[id]`'s precedent — a segment that cannot be one of ours 404s without a
 * query. Then `getNinaImageJobDetail(userId, id)`, which puts `user_id` in the `WHERE`, so a
 * foreign id and a nonexistent id come back as the same `null` and 404 identically. Nothing here
 * discloses which ids exist.
 *
 * `PageProps<'/nina/jobs/[id]'>` is Next 16's globally available helper — not an import — and
 * `params` is a PROMISE that must be awaited
 * (`node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/page.md`, "Page Props
 * Helper"). The types are generated by `next typegen`, which `npm run typecheck` runs first; the
 * route is new, so a bare `tsc --noEmit` against a stale `.next/types` will not know this literal.
 *
 * ── WHERE THE JUMP IS DECIDED ─────────────────────────────────────────────────────────────────
 * HERE, on the server, from an ownership-scoped resolution — never in the component. The target is
 * the EARLIEST bubble, across every session, whose message attached this job's photograph: the
 * photograph row `getNinaJobPhoto` already resolved for the icon is handed to
 * `getNinaJobPhotoBubble`, which walks the original and every reference of it forward in
 * conversation order. `planJobJump` turns what is left (a live bubble; an avatar job that never
 * has one; a selfie whose photograph resolves to no live bubble — not made yet, removed, or its
 * chat gone) into one value the client renders without re-deriving anything. `args.replyToId` is
 * no longer consulted on this page at all; the redo path still carries it in the job args.
 *
 * ── WHERE THE PHOTOGRAPH IS DECIDED ───────────────────────────────────────────────────────────
 * HERE too, from an owner-scoped read (`getNinaJobPhoto`) — the same split the jump keeps, for the
 * same reason. `planJobPhoto` turns the two facts (whose job is this; does its photograph row still
 * exist) into the value the client renders.
 *
 * ── WHY SEQUENTIAL-AND-SKIPPED FOR AVATAR, AND NOT `Promise.all` ──────────────────────────────
 * `purpose` is a fact only the detail read produces, so "run the photo read in parallel with the
 * detail read" and "run no query at all for an avatar job" cannot both hold. The skip wins: an
 * avatar job's reads are empty BY CONSTRUCTION (`finishAvatar` writes no carrier message, so no
 * `turn_id` ever names one), and avatar jobs are the common case on this page — every avatar
 * generation is one, while chat selfies are capped at six a day — so the unconditional parallel
 * spelling would spend the query exactly where it is worth least. Two sequential reads for a
 * selfie (photograph, then its earliest bubble) is the page's whole cost, on a screen opened a
 * handful of times a day. The RULES (an avatar job never gets the icon, never gets the jump) do
 * not depend on the skip — `planJobPhoto`'s and `planJobJump`'s avatar arms hold them where a test
 * reaches them.
 *
 * `SESSION_PARAM` is imported HERE and passed down, so `?s=`'s spelling still lives in exactly one
 * place — `app/nina/page.tsx` concentrates its cross-phase dependencies the same way and says so.
 *
 * ── THE DAY LABEL IS FORMATTED ON THE SERVER ──────────────────────────────────────────────────
 * Invariant 4's habit and `sessionDayLabel`'s stated reason: a formatted instant inside a client
 * component is the hydration mismatch `app/nina/page.tsx` documents in three places.
 */
export default async function NinaJobDetailPage({ params }: PageProps<'/nina/jobs/[id]'>) {
  const userId = await requireUserId()
  const { id } = await params
  if (!isValidId(id)) notFound()

  const job = await getNinaImageJobDetail(userId, id)
  if (job === null) notFound()

  const stage = jobStage({ status: job.status, errorCode: job.errorCode })

  /* One reading of the clock for this render. The disable is the list route's, for its reason:
   * `react-hooks/purity` guards re-render idempotency and a Server Component renders once. */
  // eslint-disable-next-line react-hooks/purity -- see app/nina/jobs/page.tsx.
  const nowMs = Date.now()

  /* Skipped outright for an avatar job — see the docstring's `Promise.all` paragraph. */
  const photoRow = job.purpose === 'avatar' ? null : await getNinaJobPhoto(userId, id)
  /* The jump's target, from the photograph the icon already named: the earliest live bubble
   * carrying it, in any session. `null` for an avatar job by the same skip, and for a selfie
   * whose photograph resolves to no live bubble — `planJobJump` owns the sentence for both. */
  const bubble = photoRow === null ? null : await getNinaJobPhotoBubble(userId, photoRow.id)
  const photo = planJobPhoto({ jobId: job.id, purpose: job.purpose, imageId: photoRow?.id ?? null })

  return (
    <AppShell>
      <ScreenHeader
        title="Detail foto"
        action={
          <Link href={NINA_JOBS_HREF} className="text-[13px] font-semibold text-accent">
            SEMUA JOB
          </Link>
        }
      />
      <NinaJobDetail
        stage={stage}
        stageLabel={NINA_JOB_STAGE_LABEL[stage]}
        errorLabel={stage === 'failed' ? jobErrorLabel(job.errorCode) : null}
        purpose={job.purpose}
        mood={job.mood}
        prompt={job.prompt}
        sidecar={job.sidecar}
        seed={job.seed}
        model={job.model}
        attempts={job.attempts}
        costMicroUsd={job.costMicroUsd}
        latencyMs={job.latencyMs}
        createdAtMs={job.createdAt.getTime()}
        createdAtLabel={formatDayCompact(jakartaDayOf(job.createdAt))}
        nowMs={nowMs}
        jump={planJobJump({ purpose: job.purpose, bubble, sessionParam: SESSION_PARAM })}
        photo={photo}
      />
    </AppShell>
  )
}
