import Link from 'next/link'
import { notFound } from 'next/navigation'

import { NinaJobDetail } from '@/components/nina/NinaJobDetail'
import { AppShell, ScreenHeader } from '@/components/ui/AppShell'
import { requireUserId } from '@/lib/auth/requireUserId'
import { jakartaDayOf } from '@/lib/date/ranges'
import { formatDayCompact } from '@/lib/format'
import { isValidId } from '@/lib/id'
import { SESSION_PARAM } from '@/lib/nina/active'
import { getNinaImageJobDetail } from '@/lib/nina/imagejobs'
import {
  NINA_JOBS_HREF,
  NINA_JOB_STAGE_LABEL,
  jobErrorLabel,
  jobStage,
  planJobJump,
} from '@/lib/nina/jobview'

/**
 * `/nina/jobs/[id]` — R1's image-generation detail page.
 *
 * ── THE ID IN THE URL IS A CLAIM; THE `WHERE` IS THE FACT (INVARIANT 5) ───────────────────────
 * `isValidId` first, on `/r/[id]`'s precedent — a segment that cannot be one of ours 404s without a
 * query. Then `getNinaImageJobDetail(userId, id)`, which puts `user_id` in the `WHERE`, so a
 * foreign id and a nonexistent id come back as the same `null` and 404 identically. Nothing here
 * discloses which ids exist.
 *
 * `PageProps<'/nina/jobs/[id]'>` is Next 16's globally available helper — not an import — and
 * `params` is a PROMISE that must be awaited
 * (`node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/page.md`, "Page Props
 * Helper"). The types are generated by `next typegen`, which `npm run typecheck` runs first; the
 * route is new, so a bare `tsc --noEmit` against a stale `.next/types` will not know this literal.
 *
 * ── WHERE THE JUMP IS DECIDED ─────────────────────────────────────────────────────────────────
 * HERE, on the server, from an ownership-scoped resolution — never in the component. `planJobJump`
 * turns the four cases (a live bubble, an avatar job that never had one, a job whose args carry no
 * reply target, and a message that has been deleted or whose session was removed) into one value
 * the client renders without re-deriving anything.
 *
 * `SESSION_PARAM` is imported HERE and passed down, so `?s=`'s spelling still lives in exactly one
 * place — `app/nina/page.tsx` concentrates its cross-phase dependencies the same way and says so.
 *
 * ── THE DAY LABEL IS FORMATTED ON THE SERVER ──────────────────────────────────────────────────
 * Invariant 4's habit and `sessionDayLabel`'s stated reason: a formatted instant inside a client
 * component is the hydration mismatch `app/nina/page.tsx` documents in three places.
 */
export default async function NinaJobDetailPage({ params }: PageProps<'/nina/jobs/[id]'>) {
  const userId = await requireUserId()
  const { id } = await params
  if (!isValidId(id)) notFound()

  const job = await getNinaImageJobDetail(userId, id)
  if (job === null) notFound()

  const stage = jobStage({ status: job.status, errorCode: job.errorCode })

  /* One reading of the clock for this render. The disable is the list route's, for its reason:
   * `react-hooks/purity` guards re-render idempotency and a Server Component renders once. */
  // eslint-disable-next-line react-hooks/purity -- see app/nina/jobs/page.tsx.
  const nowMs = Date.now()

  return (
    <AppShell>
      <ScreenHeader
        title="Detail foto"
        action={
          <Link href={NINA_JOBS_HREF} className="text-[13px] font-semibold text-accent">
            SEMUA JOB
          </Link>
        }
      />
      <NinaJobDetail
        stage={stage}
        stageLabel={NINA_JOB_STAGE_LABEL[stage]}
        errorLabel={stage === 'failed' ? jobErrorLabel(job.errorCode) : null}
        purpose={job.purpose}
        scene={job.scene}
        mood={job.mood}
        prompt={job.prompt}
        sidecar={job.sidecar}
        seed={job.seed}
        model={job.model}
        attempts={job.attempts}
        costMicroUsd={job.costMicroUsd}
        latencyMs={job.latencyMs}
        createdAtMs={job.createdAt.getTime()}
        createdAtLabel={formatDayCompact(jakartaDayOf(job.createdAt))}
        nowMs={nowMs}
        jump={planJobJump({
          purpose: job.purpose,
          replyToId: job.replyToId,
          replySessionId: job.replySessionId,
          sessionParam: SESSION_PARAM,
        })}
      />
    </AppShell>
  )
}
