import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { installFakeDb, tableRow, uninstallFakeDb, type FakeDb } from './support/fakeDb'

/**
 * ██ THE APP'S CORE SECURITY REGRESSION GUARD ██
 *
 * run_splits, run_zones and run_photos carry no user_id. If a correlated EXISTS back to `runs`
 * ever goes missing from one of these predicates, any signed-in user can read or mutate another
 * user's splits by guessing a 12-character run id — and nothing else in the test suite would
 * notice, because every query would still return plausible rows.
 *
 * These tests read the SQL actually generated by the Postgres dialect. They fail on a missing
 * predicate, a predicate against the wrong table, and on `assertRunOwned` leaking WHICH of
 * "missing" or "not yours" happened.
 */

type Queries = typeof import('@/lib/db/queries')

let fake: FakeDb
let q: Queries

beforeEach(async () => {
  vi.resetModules()
  fake = installFakeDb()
  q = await import('@/lib/db/queries')
})

afterEach(() => {
  uninstallFakeDb()
  vi.resetModules()
})

describe('ownership predicates', () => {
  it('runSplitOwnedBy correlates run_splits.run_id to runs.user_id', async () => {
    const { and, eq } = await import('drizzle-orm')
    const { db } = await import('@/lib/db/index')
    const { runSplits } = await import('@/lib/db/schema')

    const { sql } = db
      .select()
      .from(runSplits)
      .where(and(eq(runSplits.km, 1), q.runSplitOwnedBy('u1')))
      .toSQL()

    expect(sql).toContain('exists')
    expect(sql).toContain('"runs"."id" = "run_splits"."run_id"')
    expect(sql).toContain('"runs"."user_id" = $')
  })

  it('runZoneOwnedBy correlates run_zones.run_id to runs.user_id', async () => {
    const { and, eq } = await import('drizzle-orm')
    const { db } = await import('@/lib/db/index')
    const { runZones } = await import('@/lib/db/schema')

    const { sql } = db
      .select()
      .from(runZones)
      .where(and(eq(runZones.zone, 5), q.runZoneOwnedBy('u1')))
      .toSQL()

    expect(sql).toContain('"runs"."id" = "run_zones"."run_id"')
    expect(sql).toContain('"runs"."user_id" = $')
  })

  it('runPhotoOwnedBy accepts EITHER parent, because a photo outlives having only one', async () => {
    const { and, eq } = await import('drizzle-orm')
    const { db } = await import('@/lib/db/index')
    const { runPhotos } = await import('@/lib/db/schema')

    const { sql } = db
      .select()
      .from(runPhotos)
      .where(and(eq(runPhotos.id, 'p1'), q.runPhotoOwnedBy('u1')))
      .toSQL()

    // Before the review commit a photo has only an extraction (R-1); after it, also a run.
    expect(sql).toContain('"extractions"."id" = "run_photos"."extraction_id"')
    expect(sql).toContain('"extractions"."user_id" = $')
    expect(sql).toContain('"runs"."id" = "run_photos"."run_id"')
    expect(sql).toContain('"runs"."user_id" = $')
    expect(sql.toLowerCase()).toContain(' or ')
  })

  it('every ownership predicate names runs.user_id — none is a bare id comparison', async () => {
    const { and, eq } = await import('drizzle-orm')
    const { db } = await import('@/lib/db/index')
    const { runPhotos, runSplits, runZones } = await import('@/lib/db/schema')

    const statements = [
      db.select().from(runSplits).where(q.runSplitOwnedBy('u1')).toSQL().sql,
      db.select().from(runZones).where(q.runZoneOwnedBy('u1')).toSQL().sql,
      db
        .select()
        .from(runPhotos)
        .where(and(eq(runPhotos.id, 'p1'), q.runPhotoOwnedBy('u1')))
        .toSQL().sql,
    ]
    for (const statement of statements) {
      expect(statement).toMatch(/"user_id" = \$\d/)
    }
  })
})

describe('assertRunOwned', () => {
  it('filters on BOTH id and user_id in one statement', async () => {
    fake.enqueue([[1]])
    await q.assertRunOwned('u1', 'run_abc')
    const { sql, params } = fake.only()
    expect(sql).toContain('"runs"."id" = $')
    expect(sql).toContain('"runs"."user_id" = $')
    expect(params).toContain('run_abc')
    expect(params).toContain('u1')
    expect(sql).toContain('limit')
  })

  it('throws NotFoundError when the run is missing', async () => {
    fake.enqueue([])
    await expect(q.assertRunOwned('u1', 'nope')).rejects.toBeInstanceOf(q.NotFoundError)
  })

  it('throws the SAME NotFoundError when the run exists but belongs to someone else', async () => {
    // The fake returns no rows because the user_id predicate excluded the row — indistinguishable
    // from "no such run", which is the point: anything else is an id-enumeration oracle.
    fake.enqueue([])
    const missing = await q.assertRunOwned('u2', 'nope').catch((e: Error) => e)
    fake.reset()
    fake.enqueue([])
    const notMine = await q.assertRunOwned('u2', 'run_of_u1').catch((e: Error) => e)

    expect((missing as Error).name).toBe('NotFoundError')
    expect((notMine as Error).message).toBe((missing as Error).message)
  })
})

describe('assertExtractionOwned', () => {
  it('scopes by user_id and throws NotFoundError otherwise', async () => {
    fake.enqueue([])
    await expect(q.assertExtractionOwned('u1', 'x1')).rejects.toBeInstanceOf(q.NotFoundError)
    expect(fake.only().sql).toContain('"extractions"."user_id" = $')
  })
})

describe('the ownership predicate is present on every child-table mutation', () => {
  it('setPhotoExcludedFromShare cannot be aimed at another user’s photo', async () => {
    fake.enqueue([[1]])
    await q.setPhotoExcludedFromShare('u1', 'p1', true)
    const { sql } = fake.only()
    expect(sql).toMatch(/^update "run_photos"/)
    expect(sql).toContain('"run_photos"."id" = $')
    expect(sql).toContain('"user_id" = $')
    // No SELECT-then-UPDATE: one statement, so there is no TOCTOU window.
    expect(fake.queries).toHaveLength(1)
  })

  it('deletePhoto carries the predicate and returns the pathname for blob cleanup', async () => {
    fake.enqueue([['screens/abc.jpg']])
    const result = await q.deletePhoto('u1', 'p1')
    expect(result).toEqual({ pathname: 'screens/abc.jpg' })
    const { sql } = fake.only()
    expect(sql).toMatch(/^delete from "run_photos"/)
    expect(sql).toContain('"user_id" = $')
    expect(sql).toContain('returning')
  })

  it('updatePhotoBlobLocation (R-15 rotation) carries the predicate', async () => {
    fake.enqueue([['p1']])
    await q.updatePhotoBlobLocation('u1', 'p1', { blobUrl: 'https://b/x', pathname: 'x' })
    expect(fake.only().sql).toContain('"user_id" = $')
  })
})

describe('getRunDetail refuses another user’s run without leaking that it exists', () => {
  it('returns null rather than throwing', async () => {
    fake.enqueue([], [], [], [])
    await expect(q.getRunDetail('u2', 'run_of_u1')).resolves.toBeNull()
  })

  it('scopes the run row and all three child selects', async () => {
    fake.enqueue([tableRow((await import('@/lib/db/schema')).runs, { id: 'r1' })], [], [], [])
    await q.getRunDetail('u1', 'r1')
    expect(fake.queries).toHaveLength(4)
    for (const query of fake.queries) {
      expect(query.sql).toMatch(/"user_id" = \$\d/)
    }
  })
})
